-- =============================================================================
-- Skyline Skydiving Portal — Migration 0001
-- Initial schema for the portal's PostgreSQL database (DigitalOcean Managed).
--
-- This file is the SQL implementation of the finalised DBML schema in the
-- developer handoff. Designed as the seed of the wider Skyline data stack.
--
-- Notes:
--   * Integer auto-increment primary keys throughout (matching the DBML).
--   * Profile data lives inline on `users` (no separate user_profiles table).
--   * Heights and weights stored in metric (cm, kg); the frontend displays
--     imperial.
--   * `users.hash_algorithm` lets the auth layer verify against either phpass
--     (WordPress legacy) or bcrypt during the planned cutover, then re-hashes
--     to bcrypt invisibly on next successful login.
--   * Booking snapshot columns (`*_at_booking`) preserve the user's data as
--     it was at booking time, for audit and safety.
--   * Charity pricing variants live in `charity_codes` with valid_from /
--     valid_to date ranges, not a "current" boolean — historical bookings can
--     identify which code applied at their time.
--
-- Target: PostgreSQL 13+ (DigitalOcean Managed Postgres).
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- Shared trigger function: bumps updated_at on every UPDATE
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- users
-- One row per person ever. Profile data is inline; the booking snapshot
-- (in `bookings`) preserves the historical record.
-- =============================================================================
CREATE TABLE users (
  user_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email           TEXT NOT NULL UNIQUE,
  password_hash   TEXT NOT NULL,
  hash_algorithm  TEXT NOT NULL,
  first_name      TEXT,
  last_name       TEXT,
  dob             DATE,
  gender          TEXT,
  phone_number    TEXT,
  address_1       TEXT,
  address_2       TEXT,
  town            TEXT,
  county          TEXT,
  postcode        TEXT,
  height_cm       NUMERIC,
  weight_kg       NUMERIC,
  fundraising_url TEXT,
  terms_agreed_at TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN users.hash_algorithm IS 'phpass during migration, bcrypt after';
COMMENT ON COLUMN users.height_cm      IS 'stored metric, displayed imperial';
COMMENT ON COLUMN users.weight_kg      IS 'stored metric, displayed imperial';

CREATE TRIGGER users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- venues
-- One row per airfield.
-- =============================================================================
CREATE TABLE venues (
  venue_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_name  TEXT NOT NULL,
  venue_price NUMERIC(12, 2),
  address_1   TEXT,
  address_2   TEXT,
  town        TEXT,
  county      TEXT,
  postcode    TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN venues.venue_price IS 'current price';

CREATE TRIGGER venues_updated_at
  BEFORE UPDATE ON venues
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- charities
-- Partner charity directory. Address fields are a placeholder until Attio is
-- confirmed as the source of truth.
-- =============================================================================
CREATE TABLE charities (
  charity_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  charity_name TEXT NOT NULL,
  address_1    TEXT,
  address_2    TEXT,
  town         TEXT,
  county       TEXT,
  postcode     TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN charities.address_1 IS 'may move to Attio if confirmed';

CREATE TRIGGER charities_updated_at
  BEFORE UPDATE ON charities
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- charity_codes
-- Pricing variant per charity per booking link. Validity is a date range —
-- historical bookings identify which code applied at their booking time by
-- checking `valid_from` ... `valid_to`.
-- =============================================================================
CREATE TABLE charity_codes (
  charity_code        TEXT PRIMARY KEY,
  charity_id          INTEGER NOT NULL REFERENCES charities(charity_id),
  deposit             NUMERIC(12, 2),
  sponsorship_target  NUMERIC(12, 2),
  valid_from          DATE NOT NULL,
  valid_to            DATE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN charity_codes.valid_to IS 'null means currently active';

CREATE INDEX idx_charity_codes_charity_id ON charity_codes (charity_id);

-- =============================================================================
-- bookings
-- One row per event participation. Includes the change-request state machine
-- (date and venue, independent flags) and a snapshot of the user's personal
-- data at booking time for audit and safety.
-- =============================================================================
CREATE TABLE bookings (
  booking_number          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                 INTEGER NOT NULL REFERENCES users(user_id),
  venue_id                INTEGER REFERENCES venues(venue_id),
  charity_id              INTEGER REFERENCES charities(charity_id),
  charity_code            TEXT    REFERENCES charity_codes(charity_code),
  booking_date            DATE NOT NULL,
  event_date              DATE,
  booking_status          TEXT NOT NULL DEFAULT 'active',

  -- Change-request flow (date and venue, independent flags)
  original_date_request_1 DATE,
  original_date_request_2 DATE,
  new_date_request_1      DATE,
  new_date_request_2      DATE,
  new_venue_request       INTEGER REFERENCES venues(venue_id),
  date_change_pending     BOOLEAN DEFAULT FALSE,
  venue_change_pending    BOOLEAN DEFAULT FALSE,

  -- Snapshot of user data at booking time (audit / safety)
  phone_at_booking        TEXT,
  address_1_at_booking    TEXT,
  address_2_at_booking    TEXT,
  town_at_booking         TEXT,
  county_at_booking       TEXT,
  postcode_at_booking     TEXT,
  height_cm_at_booking    NUMERIC,
  weight_kg_at_booking    NUMERIC,

  price_paid              NUMERIC(12, 2),
  marketing_source        TEXT,
  notes                   TEXT,
  terms_agreed_at         TIMESTAMPTZ,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_bookings_user_id           ON bookings (user_id);
CREATE INDEX idx_bookings_venue_id          ON bookings (venue_id);
CREATE INDEX idx_bookings_charity_id        ON bookings (charity_id);
CREATE INDEX idx_bookings_charity_code      ON bookings (charity_code);
CREATE INDEX idx_bookings_new_venue_request ON bookings (new_venue_request);
CREATE INDEX idx_bookings_event_date        ON bookings (event_date);

CREATE TRIGGER bookings_updated_at
  BEFORE UPDATE ON bookings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- payments
-- Payments received against a booking.
-- =============================================================================
CREATE TABLE payments (
  payment_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_number INTEGER NOT NULL REFERENCES bookings(booking_number),
  payment_date   DATE NOT NULL,
  amount         NUMERIC(12, 2) NOT NULL,
  payment_method TEXT,
  item           TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_payments_booking_number ON payments (booking_number);

-- =============================================================================
-- sponsorship_collected
-- Fundraising raised against a booking.
-- =============================================================================
CREATE TABLE sponsorship_collected (
  sponsorship_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_number   INTEGER NOT NULL REFERENCES bookings(booking_number),
  collected_date   DATE NOT NULL,
  amount           NUMERIC(12, 2) NOT NULL,
  transaction_type TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_sponsorship_collected_booking_number
  ON sponsorship_collected (booking_number);

-- =============================================================================
-- correspondence
-- Communications log per booking.
-- =============================================================================
CREATE TABLE correspondence (
  correspondence_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_number    INTEGER NOT NULL REFERENCES bookings(booking_number),
  date              DATE NOT NULL,
  method            TEXT,
  item              TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN correspondence.method IS 'email, sms, post, call';

CREATE INDEX idx_correspondence_booking_number ON correspondence (booking_number);

-- =============================================================================
-- sessions
-- Active server-side sessions. session_id is a random token issued on login;
-- the value stored in the HTTP-only cookie.
-- =============================================================================
CREATE TABLE sessions (
  session_id     TEXT PRIMARY KEY,
  user_id        INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_active_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at     TIMESTAMPTZ NOT NULL,
  ip_address     TEXT,
  user_agent     TEXT
);

COMMENT ON COLUMN sessions.session_id IS 'random token';

CREATE INDEX idx_sessions_user_id    ON sessions (user_id);
CREATE INDEX idx_sessions_expires_at ON sessions (expires_at);

-- =============================================================================
-- password_resets
-- Time-limited reset tokens (30-minute TTL set by the application).
-- =============================================================================
CREATE TABLE password_resets (
  reset_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  token      TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at    TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN password_resets.used_at IS 'null if not used';

CREATE INDEX idx_password_resets_user_id    ON password_resets (user_id);
CREATE INDEX idx_password_resets_expires_at ON password_resets (expires_at);

-- =============================================================================
-- email_change_confirmations
-- Pending email-change requests. Link is sent to the NEW email; change is
-- only applied when the link is clicked.
-- =============================================================================
CREATE TABLE email_change_confirmations (
  confirmation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  new_email       TEXT NOT NULL,
  token           TEXT NOT NULL UNIQUE,
  expires_at      TIMESTAMPTZ NOT NULL,
  confirmed_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN email_change_confirmations.confirmed_at IS 'null if not confirmed';

CREATE INDEX idx_email_change_confirmations_user_id    ON email_change_confirmations (user_id);
CREATE INDEX idx_email_change_confirmations_expires_at ON email_change_confirmations (expires_at);

COMMIT;

-- -----------------------------------------------------------------------------
-- Quick verification (run separately if you want):
--   SELECT table_name FROM information_schema.tables
--   WHERE table_schema = 'public' ORDER BY table_name;
-- -----------------------------------------------------------------------------
